/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ba869f74-7b56-4c34-9199-9b3b29c1f534",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_gsLeDUsSD",
    "aws_user_pools_web_client_id": "5p2clp2l3jgk2a9aeg8j4fpnv",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://kdzs6tkkzrguhakgcqmz6gptfu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wjombgarzzf2flbjtmau3yl7sa",
    "aws_user_files_s3_bucket": "clientd1d81a2bba94427a90c5691844bc5a71194658-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
